platform :ios, '7.0'

target "WETECHCushion" do

pod 'AFNetworking', '~> 2.2'
pod 'AFDownloadRequestOperation', '~> 2.0'
pod 'AFNetworking-RACExtensions', '~> 0.1'
pod 'AutoScrollLabel', '~> 0.2'
#pod 'Appirater', '~> 2.0'
pod 'Base64nl', '~> 1.2'

pod 'MRProgress', '~> 0.7'
pod 'MBProgressHUD', '~> 0.8'
pod 'Masonry', '~> 0.5'
pod 'MarqueeLabel'    

#pod 'ProgressHUD', '< 2.3'

pod 'SBJson', '< 4.0'

pod 'UIColor-Pantone', '~> 1.0'
pod 'UIColor-Crayola', '~> 1.0'

end
